package com.chatapp.pojos;
// Generated 29-Mar-2023 16:19:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ChatSession generated by hbm2java
 */
public class ChatSession  implements java.io.Serializable {

    private int sessionId;
    private Chat chat;
    private String fileLink;
    private Date startedAt;
    private Date stoppedAt;

    public ChatSession() {
    }

	
    public ChatSession(int sessionId, Chat chat, String fileLink) {
        this.sessionId = sessionId;
        this.chat = chat;
        this.fileLink = fileLink;
    }
    
    public ChatSession(int sessionId, Chat chat, String fileLink, Date startedAt, Date stoppedAt) {
       this.sessionId = sessionId;
       this.chat = chat;
       this.fileLink = fileLink;
       this.startedAt = startedAt;
       this.stoppedAt = stoppedAt;
    }
   
    public int getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
    
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }
    
    public String getFileLink() {
        return this.fileLink;
    }
    
    public void setFileLink(String fileLink) {
        this.fileLink = fileLink;
    }
    
    public Date getStartedAt() {
        return this.startedAt;
    }
    
    public void setStartedAt(Date startedAt) {
        this.startedAt = startedAt;
    }
    
    public Date getStoppedAt() {
        return this.stoppedAt;
    }
    
    public void setStoppedAt(Date stoppedAt) {
        this.stoppedAt = stoppedAt;
    }
}


