package com.chatapp.pojos;
// Generated 30-May-2022 06:35:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chatsession generated by hbm2java
 */
public class Chatsession  implements java.io.Serializable {


     private int sessionId;
     private Chat chat;
     private String link;
     private Date startedAt;
     private Date stoppedAt;

    public Chatsession() {
    }

	
    public Chatsession(int sessionId, Chat chat, String link) {
        this.sessionId = sessionId;
        this.chat = chat;
        this.link = link;
    }
    public Chatsession(int sessionId, Chat chat, String link, Date startedAt, Date stoppedAt) {
       this.sessionId = sessionId;
       this.chat = chat;
       this.link = link;
       this.startedAt = startedAt;
       this.stoppedAt = stoppedAt;
    }
   
    public int getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(int sessionId) {
        this.sessionId = sessionId;
    }
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Date getStartedAt() {
        return this.startedAt;
    }
    
    public void setStartedAt(Date startedAt) {
        this.startedAt = startedAt;
    }
    public Date getStoppedAt() {
        return this.stoppedAt;
    }
    
    public void setStoppedAt(Date stoppedAt) {
        this.stoppedAt = stoppedAt;
    }




}


