package com.chatapp.pojos;
// Generated 29-Mar-2023 16:19:53 by Hibernate Tools 4.3.1



/**
 * SubscriptionId generated by hbm2java
 */
public class SubscriptionId  implements java.io.Serializable {

    private int userId;
    private int chatId;

    public SubscriptionId() {
    }

    public SubscriptionId(int userId, int chatId) {
       this.userId = userId;
       this.chatId = chatId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    public int getChatId() {
        return this.chatId;
    }
    
    public void setChatId(int chatId) {
        this.chatId = chatId;
    }

    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof SubscriptionId) ) return false;
        SubscriptionId castOther = ( SubscriptionId ) other; 

        return (this.getUserId()==castOther.getUserId()) && (this.getChatId()==castOther.getChatId());
    }
   
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUserId();
        result = 37 * result + this.getChatId();
        return result;
    }   
}


