package com.chatapp.pojos;
// Generated 30-May-2022 06:35:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Subscription generated by hbm2java
 */
public class Subscription  implements java.io.Serializable {


     private SubscriptionId id;
     private Chat chat;
     private User user;
     private Date registeredAt;

    public Subscription() {
    }

	
    public Subscription(SubscriptionId id, Chat chat, User user) {
        this.id = id;
        this.chat = chat;
        this.user = user;
    }
    public Subscription(SubscriptionId id, Chat chat, User user, Date registeredAt) {
       this.id = id;
       this.chat = chat;
       this.user = user;
       this.registeredAt = registeredAt;
    }
   
    public SubscriptionId getId() {
        return this.id;
    }
    
    public void setId(SubscriptionId id) {
        this.id = id;
    }
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getRegisteredAt() {
        return this.registeredAt;
    }
    
    public void setRegisteredAt(Date registeredAt) {
        this.registeredAt = registeredAt;
    }




}


