package com.chatapp.pojos;
// Generated 30-May-2022 06:35:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String role;
     private String email;
     private String username;
     private String password;
     private String nickname;
     private byte[] avatar;
     private Set subscriptions = new HashSet(0);

    public User() {
    }

	
    public User(String role, String email, String username, String password, String nickname) {
        this.role = role;
        this.email = email;
        this.username = username;
        this.password = password;
        this.nickname = nickname;
    }
    public User(String role, String email, String username, String password, String nickname, byte[] avatar, Set subscriptions) {
       this.role = role;
       this.email = email;
       this.username = username;
       this.password = password;
       this.nickname = nickname;
       this.avatar = avatar;
       this.subscriptions = subscriptions;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNickname() {
        return this.nickname;
    }
    
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    public byte[] getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }
    public Set getSubscriptions() {
        return this.subscriptions;
    }
    
    public void setSubscriptions(Set subscriptions) {
        this.subscriptions = subscriptions;
    }




}


